import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os # Import os module for path manipulation
from datetime import datetime

def create_energy_distribution_plot(csv_path: str, output_dir: str) -> str:
    """
    Generates and saves a histogram plot of energy distribution from a CSV file.

    Args:
        csv_path (str): Path to the input CSV file generated by main_new.py.
        output_dir (str): Directory to save the energy distribution plot.

    Returns:
        str: Path to the saved energy distribution plot image file.
    """
    try:
        df = pd.read_csv(csv_path)
        df = df.to_numpy()

        energy_values = []
        for i in df:
            if i[5] == 0: # Assuming column index 5 contains energy values
                pass
            else:
                energy_values.append(i[5])

        plt.figure(figsize=(8, 6)) # Create a new figure for the plot
        plt.hist(energy_values, bins=30, color='skyblue', edgecolor='black')  # Adjust bins as needed
        plt.xlabel('Misorientation energy (a.u)')
        plt.ylabel('Frequency')
        plt.title('Energy Distribution for deformed sample')
        plt.grid(False)  # Add grid lines

        # Generate output file path with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S") # Import datetime if not already imported in this file
        output_filename = f"energy_distribution_{timestamp}.png"
        output_path = os.path.join(output_dir, output_filename)

        plt.savefig(output_path, dpi=300) # Save plot to file in the specified output directory
        plt.close() # Close the plot to free memory

        return output_path # Return the path to the saved image

    except FileNotFoundError:
        raise FileNotFoundError(f"CSV file not found at: {csv_path}")
    except pd.errors.EmptyDataError:
        raise pd.errors.EmptyDataError(f"No data in CSV file at: {csv_path}")
    except Exception as e:
        raise RuntimeError(f"Error generating energy distribution plot: {str(e)}")

if __name__ == "__main__":
    # Example usage (for testing purposes):
    # Replace 'path_to_crystallography_analysis_csv' with the actual path to your CSV output file
    test_csv_path = 'output/crystallography_analysis_20240229_165352.csv' # Example path
    output_directory = 'output' # Example output directory
    try:
        plot_path = create_energy_distribution_plot(test_csv_path, output_directory)
        print(f"Energy distribution plot saved at: {plot_path}")
    except Exception as e:
        print(f"Error: {e}")